{{- if .Values.ingress.enabled }}
{{- $domain := default "" .Values.ingress.domain -}}
{{- $airflowHost := default "" .Values.ingress.host.airflow -}}
{{- if eq $airflowHost "" -}}
  {{- if ne $domain "" -}}
    {{- $airflowHost = printf "%s.%s" .Values.ingress.subdomain.airflow $domain -}}
  {{- else -}}
    {{- $airflowHost = .Values.ingress.subdomain.airflow -}}
  {{- end -}}
{{- end -}}

{{- $mlflowHost := default "" .Values.ingress.host.mlflow -}}
{{- if eq $mlflowHost "" -}}
  {{- if ne $domain "" -}}
    {{- $mlflowHost = printf "%s.%s" .Values.ingress.subdomain.mlflow $domain -}}
  {{- else -}}
    {{- $mlflowHost = .Values.ingress.subdomain.mlflow -}}
  {{- end -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ $airflowHost | quote }}
      http:
        paths:
          # Airflow: directamente en la ra√≠z
          - path: "/" 
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.airflowServiceName }}
                port:
                  number: {{ .Values.ingress.airflowServicePort }}
    - host: {{ $mlflowHost | quote }}
      http:
        paths:
          # MLflow en /mlflow
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.mlflowServiceName }}
                port:
                  number: {{ .Values.ingress.mlflowServicePort }}
{{- end }}
