# values.yaml para MLflow
backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgres-postgresql
    port: 5432
    database: mlflow
    user: postgres
    password: postgres 

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio-service:9000
  MLFLOW_S3_IGNORE_TLS: "true"
  MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow.localhost"

extraSecretNamesForEnvFrom:
  - env-secret